[tool.poetry]
name = "slowpoke-finder"
version = "0.1.0"
description = "CLI-инструмент для поиска самых медленных шагов в логах тестов Playwright/Selenium"
authors = ["Анастасия Литвиненко"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "slowpoke_finder" }
]

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.12.0"

[tool.poetry.scripts]
slowpoke-finder = "slowpoke_finder.cli:app"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
ruff = "^0.4.2"
black = "^24.4.2"
mypy = "^1.10.0"

# Если появятся отчёты:
# jinja2 = "^3.1.0"
# matplotlib = "^3.7.0"
pre-commit = "^4.2.0"
